-- Generated by scripts/build_db.py from hazus_curves/schema.py.
-- Target: postgresql. Do not edit by hand.

-- One row per damage/vulnerability curve.
CREATE TABLE IF NOT EXISTS curves (
    curve_id TEXT NOT NULL,
    peril TEXT NOT NULL,
    hazus_version TEXT NOT NULL,
    damage_type TEXT NOT NULL,
    occupancy TEXT,
    building_type TEXT,
    source_agency TEXT,
    description TEXT,
    defect_flag TEXT,
    defect_verified TEXT,
    source_file TEXT NOT NULL,
    source_table TEXT NOT NULL,
    source_row_id TEXT NOT NULL,
    PRIMARY KEY (curve_id)
);

CREATE INDEX IF NOT EXISTS curves_peril_occ ON curves (peril, occupancy);

CREATE INDEX IF NOT EXISTS curves_srcagency ON curves (source_agency);

-- Tidy long-format curve points. One row per (curve, x).
CREATE TABLE IF NOT EXISTS curve_points (
    curve_id TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION,
    PRIMARY KEY (curve_id, x)
);

-- Peril-specific keying dimensions. This is what makes the unified schema lossless and peril-pluggable.
CREATE TABLE IF NOT EXISTS curve_attributes (
    curve_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    PRIMARY KEY (curve_id, key)
);

CREATE INDEX IF NOT EXISTS curve_attr_kv ON curve_attributes (key, value);

-- What x and y actually mean, per peril. Consumers should read this rather than assume units.
CREATE TABLE IF NOT EXISTS curve_kind (
    peril TEXT NOT NULL,
    damage_type TEXT NOT NULL,
    x_name TEXT NOT NULL,
    x_units TEXT NOT NULL,
    y_name TEXT NOT NULL,
    y_units TEXT NOT NULL,
    interpolation TEXT NOT NULL,
    notes TEXT,
    PRIMARY KEY (peril, damage_type)
);

-- Hazus's own default curve selection. Note that Hazus 7.0 changed the coastal selection rule (depth-limited at 3 ft and 6 ft) without changing any curve; that rule is recorded here, not as curve data.
CREATE TABLE IF NOT EXISTS assignment_rules (
    rule_id TEXT NOT NULL,
    peril TEXT NOT NULL,
    hazus_version TEXT NOT NULL,
    damage_type TEXT NOT NULL,
    occupancy TEXT,
    flood_zone TEXT,
    stories TEXT,
    basement TEXT,
    curve_id TEXT,
    source_file TEXT NOT NULL,
    source_table TEXT NOT NULL,
    notes TEXT,
    PRIMARY KEY (rule_id)
);

-- Hazus occupancy classes. Source values are space-padded; stripped on load.
CREATE TABLE IF NOT EXISTS dim_occupancy (
    occupancy TEXT NOT NULL,
    category TEXT,
    description TEXT,
    PRIMARY KEY (occupancy)
);

-- Hazus specific building types (hurricane).
CREATE TABLE IF NOT EXISTS dim_building_type (
    building_type TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (building_type)
);

-- Integrity record for every upstream file, copied from raw/MANIFEST.json so the database is self-describing once detached from the repo.
CREATE TABLE IF NOT EXISTS provenance (
    source_file TEXT NOT NULL,
    url TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    bytes INTEGER NOT NULL,
    retrieved_at TEXT NOT NULL,
    hazus_version TEXT NOT NULL,
    note TEXT,
    PRIMARY KEY (source_file)
);
