-- Generated by scripts/build_db.py from hazus_curves/schema.py.
-- Target: snowflake. Do not edit by hand.

-- One row per damage/vulnerability curve.
CREATE TABLE IF NOT EXISTS curves (
    curve_id VARCHAR NOT NULL,
    peril VARCHAR NOT NULL,
    hazus_version VARCHAR NOT NULL,
    damage_type VARCHAR NOT NULL,
    occupancy VARCHAR,
    building_type VARCHAR,
    source_agency VARCHAR,
    description VARCHAR,
    defect_flag VARCHAR,
    defect_verified VARCHAR,
    source_file VARCHAR NOT NULL,
    source_table VARCHAR NOT NULL,
    source_row_id VARCHAR NOT NULL,
    PRIMARY KEY (curve_id)
);

-- Tidy long-format curve points. One row per (curve, x).
CREATE TABLE IF NOT EXISTS curve_points (
    curve_id VARCHAR NOT NULL,
    x FLOAT NOT NULL,
    y FLOAT,
    PRIMARY KEY (curve_id, x)
);

-- Peril-specific keying dimensions. This is what makes the unified schema lossless and peril-pluggable.
CREATE TABLE IF NOT EXISTS curve_attributes (
    curve_id VARCHAR NOT NULL,
    key VARCHAR NOT NULL,
    value VARCHAR,
    PRIMARY KEY (curve_id, key)
);

-- What x and y actually mean, per peril. Consumers should read this rather than assume units.
CREATE TABLE IF NOT EXISTS curve_kind (
    peril VARCHAR NOT NULL,
    damage_type VARCHAR NOT NULL,
    x_name VARCHAR NOT NULL,
    x_units VARCHAR NOT NULL,
    y_name VARCHAR NOT NULL,
    y_units VARCHAR NOT NULL,
    interpolation VARCHAR NOT NULL,
    notes VARCHAR,
    PRIMARY KEY (peril, damage_type)
);

-- Hazus's own default curve selection. Note that Hazus 7.0 changed the coastal selection rule (depth-limited at 3 ft and 6 ft) without changing any curve; that rule is recorded here, not as curve data.
CREATE TABLE IF NOT EXISTS assignment_rules (
    rule_id VARCHAR NOT NULL,
    peril VARCHAR NOT NULL,
    hazus_version VARCHAR NOT NULL,
    damage_type VARCHAR NOT NULL,
    occupancy VARCHAR,
    flood_zone VARCHAR,
    stories VARCHAR,
    basement VARCHAR,
    curve_id VARCHAR,
    source_file VARCHAR NOT NULL,
    source_table VARCHAR NOT NULL,
    notes VARCHAR,
    PRIMARY KEY (rule_id)
);

-- Which flood zones Hazus flags a curve as applicable to. IMPORTANT: Hazus only publishes zone flags for the curves it assigns by default -- 47 of 597 structure curves in Hazus 4.0. The remainder are alternates a Hazus user selects manually and carry no zone assignment in any published table. Absence from this table therefore means 'Hazus states no zone', NOT 'not applicable'.
CREATE TABLE IF NOT EXISTS curve_zone_applicability (
    curve_id VARCHAR NOT NULL,
    flood_zone VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_table VARCHAR NOT NULL,
    PRIMARY KEY (curve_id, flood_zone)
);

-- Decomposes Hazus's geographic applicability cases into the territories each one covers. Hazus cases are SET-VALUED -- 'ContUS+Hawaii' applies in both CONUS and Hawaii -- so filtering by case equality silently excludes most applicable curves. Join through this table and match on territory instead.
CREATE TABLE IF NOT EXISTS dim_geographic_case (
    case_name VARCHAR NOT NULL,
    territory VARCHAR NOT NULL,
    case_description VARCHAR,
    PRIMARY KEY (case_name, territory)
);

-- Hazus occupancy classes. Source values are space-padded; stripped on load.
CREATE TABLE IF NOT EXISTS dim_occupancy (
    occupancy VARCHAR NOT NULL,
    category VARCHAR,
    description VARCHAR,
    PRIMARY KEY (occupancy)
);

-- Hazus specific building types (hurricane).
CREATE TABLE IF NOT EXISTS dim_building_type (
    building_type VARCHAR NOT NULL,
    description VARCHAR,
    PRIMARY KEY (building_type)
);

-- Integrity record for every upstream file, copied from raw/MANIFEST.json so the database is self-describing once detached from the repo.
CREATE TABLE IF NOT EXISTS provenance (
    source_file VARCHAR NOT NULL,
    url VARCHAR NOT NULL,
    sha256 VARCHAR NOT NULL,
    bytes NUMBER(38,0) NOT NULL,
    retrieved_at VARCHAR NOT NULL,
    hazus_version VARCHAR NOT NULL,
    note VARCHAR,
    PRIMARY KEY (source_file)
);
